config/routes.rb
Rails.application.routes.draw do
  get 'account/logout'

  root to: 'today#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/account_controller.rb
class AccountController < ApplicationController
  def logout
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/today_controller.rb
class TodayController < ApplicationController
  def index
  end
end

app/helpers/account_helper.rb
module AccountHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/today_helper.rb
module TodayHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MonkeyTasks</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/2.2.2/build/reset-fonts-grids/reset-fonts-grids.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="content">
      <div id="header">
        <%= image_tag 'monkeyhead.gif' %>
        <%= image_tag 'monkeytasks.gif' %>
      </div> <!-- End header -->
      <ul id="topnav">
        <li>
          <%= link_to 'Today', root_path %>
        </li>
        <li>
          <%= link_to 'Logout', account_logout_path %>
        </li>
      </ul>
      <p class="flash_notice"><%= flash[:notice] %></p>
      <%= yield %>
    </div>
  </body>
</html>

app/views/today/index.html.erb
<div id="primary">
  <div id="add_task"> </div>
  <div id='main'>
    <h1>Today's Tasks</h1>
    <ul id="todo-list">
      <li>test</li>
      <li>test2</li>
    </ul>
  </div>
</div>
<div id='sidebar'>
  <div class="sidebar-tasks">
    <h1>Overdue Tasks</h1>
  </div>
  <div class="sidebar-tasks">
    <h1>Due Today </h1>
  </div>
  <div class="sidebar-tasks">
    <h1>Upcoming Tasks</h1>
  </div>
</div>